# Generated by Django 4.1.4 on 2022-12-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='facebook_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='linkedin_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='thumbnail',
            field=models.ImageField(default='nodp.png', upload_to='profiles'),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='twitter_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='website_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='youtube_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='NULL.png', upload_to='thumbnails'),
        ),
    ]
