# Generated by Django 4.1.4 on 2022-12-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_thumbnail_profileinfo_dp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='dp',
            new_name='display_pictute',
        ),
    ]
