# Generated by Django 4.1.4 on 2022-12-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_dp_profileinfo_display_pictute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='display_pictute',
            new_name='display_picture',
        ),
    ]
