# Generated by Django 4.0 on 2023-10-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.IntegerField(choices=[('Unspecified', 'Unspecified'), (1, 'Spirituality'), (2, 'Technology'), (3, 'Culture'), (4, 'Philosophy'), (5, 'Fun'), (6, 'Fiction')], default=0),
        ),
    ]
