# Generated by Django 4.1.4 on 2023-11-18 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='follows',
            field=models.ManyToManyField(related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
    ]
