# Generated by Django 4.1.4 on 2023-12-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='isGoogleUser',
            field=models.BooleanField(default=False),
        ),
    ]
