# Generated by Django 4.0 on 2023-12-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_profileinfo_issubcriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='isSubcriber',
            new_name='isSubscriber',
        ),
    ]
